version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=usmobile
      - SPRING_DATA_MONGODB_URI=mongodb+srv://usmobile:usmobile-interview-process@usmobile.n7up8.mongodb.net/usmobile?retryWrites=true&w=majority&appName=usmobile
      - SPRING_DATA_MONGODB_DATABASE=usmobile
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=usmobile
      - MONGO_INITDB_ROOT_PASSWORD=usmobile-interview-process
      - MONGO_INITDB_DATABASE=usmobile
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: